WebVehiculos/Models/TipoVehiculo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVehiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoVehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoVehiculo()
        {
            this.Vehiculo = new HashSet<Vehiculo>();
        }
    
        public int idTipo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }
    }
}

WebVehiculos/Controllers/TipoVehiculoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebVehiculos.Models;

namespace WebVehiculos.Controllers
{
    [Authorize]
    public class TipoVehiculoController : Controller
    {
       VehiculosLuisEntities db=new VehiculosLuisEntities();
        // GET: TipoVehiculo
        public ActionResult Index()
        {
            

            return View(db.TipoVehiculo.ToList());
        }

        public ActionResult Alta()
        {
            return View(new TipoVehiculo());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Alta(TipoVehiculo model)
        {
            if (ModelState.IsValid)
            {
                db.TipoVehiculo.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");

            }

            return View(model);
        }

    }
}

WebVehiculos/Controllers/VehiculosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebVehiculos.Models;

namespace WebVehiculos.Controllers
{
    [Authorize]
    public class VehiculosController : Controller
    {
        VehiculosLuisEntities db=new VehiculosLuisEntities();
        // GET: Vehiculos
        public ActionResult Index(int id)
        {
            ViewBag.idTipo = id;

            var data = db.Vehiculo.Where(o => o.idTipo == id);


            return View(data);
        }

        public ActionResult Buscar(int idTipo,
            int campo, String contenido)
        {
            var data = db.Vehiculo.Where(o => o.idTipo == idTipo);
            if (campo == 1)
            {
                data = data.Where(o => o.matricula.Contains(contenido));
            }
            else
            {
                data = data.Where(o => o.marca.Contains(contenido));
            }

            return PartialView("_Listado", data.ToList());
        }

        [HttpPost]
        public ActionResult Alta(Vehiculo model)
        {
            db.Vehiculo.Add(model);
            db.SaveChanges();
            return Json(model);
        }

    }
}

WebVehiculos/Views/TipoVehiculo/Alta.cshtml
@model WebVehiculos.Models.TipoVehiculo

@{
    ViewBag.Title = "Alta";
}

<h2>Alta</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TipoVehiculo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

WebVehiculos/Views/TipoVehiculo/Index.cshtml
@model IEnumerable<WebVehiculos.Models.TipoVehiculo>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Alta", "Alta")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.descripcion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.descripcion)
        </td>
        <td>
            @Html.ActionLink("Ver vehiculos","Index",
                            "Vehiculos",new {id=item.idTipo},null);
        </td>
    </tr>
}

</table>